### ISSUE TITLE
Error on MSI sensor initialization from HASS system logs 

### ISSUE THREAD

**Issue by vadimnazaroff** [GuyKh/ims-custom-component#15]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ims/sensor.py", line 72, in async_setup_platform
    config_entry[IMS_PLATFORM] = [IMS_PLATFORMS[0]]
NameError: name 'config_entry' is not defined

**Comment by mulikg** [comment]
2023-02-20 07:29:30.058 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ims platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/ims/sensor.py", line 72, in async_setup_platform
config_entry[IMS_PLATFORM] = [IMS_PLATFORMS[0]]
NameError: name 'config_entry' is not defined

**Comment by t0mer** [comment]
Hi,
Please remove the configuration from the config.yaml and add it using the UI config flow

**Comment by vadimnazaroff** [comment]
I added it initially via UI and not via YAML
