### ISSUE TITLE
No entities are been added with v0.1.10

### ISSUE THREAD

**Issue by amitfin** [GuyKh/ims-custom-component#38]
```
Logger: homeassistant.components.weather
Source: custom_components/ims/weather.py:247
Integration: Weather (documentation, issues)
First occurred: 2:05:50 PM (2 occurrences)
Last logged: 2:05:50 PM

Error adding entities for domain weather with platform ims
Error while setting up ims platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 783, in state
    return self.condition
  File "/config/custom_components/ims/weather.py", line 247, in condition
    condition = WEATHER_CODE_TO_CONDITION[
KeyError: 'None'
```

**Comment by amitfin** [comment]
The problem is in this code:
```
    @property
    def condition(self):
        """Return the weather condition."""
        condition = WEATHER_CODE_TO_CONDITION[
            str(self._weather_coordinator.data.current_weather.weather_code)
        ]
        if not condition or condition == "Nothing":
            condition = WEATHER_CODE_TO_CONDITION[
                str(self._weather_coordinator.data.forecast.days[0].weather_code)
            ]
        return condition
```
The dictionary `WEATHER_CODE_TO_CONDITION` has None as a key, but doesn't have a key of a string with the value 'None'. However, the code cast the key to str, so it's looking for the key 'None' (a string key).

**Comment by amitfin** [comment]
Adding
`    'None': None,`
to `WEATHER_CODE_TO_CONDITION` solved the problem (but there are multiple ways to solve it, so I'll let the owners to pick the correct one for them.)

**Comment by GuyKh** [comment]
@amitfin - check with `0.1.11`

**Comment by amitfin** [comment]
Working as expected with 0.1.11. Thanks!
